database/schemas/AppSchema.js, models/AppModel.js, package.json, parsers/commentParser.js, test/helpers/chosenPostHelper/test.js, test/testHelper.js, test/validators/chosenPostValidator/test.js, utilities/helpers/chosenPostHelper.js, utilities/helpers/index.js, validator/chosenPostValidator.js, validator/index.js
Chosen post on app it's a post selected by some responsible for this user(now admin), which saved on App model and return to client.
ChosenOnePostValidator validate input data from body of comment to post, user requirement and app name.
ChosenPostHelper user validator to check data, get required data and update app with new chosen one post.
Refactor comment parser with separate handle comments and posts.
=> add helper and validator for chosen post + tests, refactor commentParser

database/schemas/UserSchema.js
=> fix default user notifications_last_timestamp

utilities/redis/unusedKeysCollector.js
increase max keys scan on delete redis unused keys
=> add limit on scan unused redis refs

validator/wobjectValidator.js
add validate to limit max rating value to 10 points
=> add validate on rating value

database/schemas/PostSchema.js, models/PostModel.js, package-lock.json, parsers/mainParser.js, parsers/userParsers.js, parsers/voteParser.js, test/factories/Post/postFactory.js, test/models/PostModel/test.js, test/parsers/userParsers/test.js
reblog post parse like blank post with some key values that duplicated from source post(like language or wobjects) and write to db  with author - author reblog and reblog_to field with refereces to source post({author, permlink})
=> add parser on reblog post

database/schemas/ObjectTypeSchema.js, package.json, test/factories/AppendObject/AppendObjectFactory.js, test/factories/ObjectType/ObjectTypeFactory.js, test/testHelper.js, test/validators/appendObjectValidator/test.js, validator/appendObjectValidator.js
add check on object type blacklist includes validating append
=> add appendWobject validation on name depends on object type

parsers/postWithObjectParser.js, test/test.js, test/validators/postWithWobjValidator/test.js, validator/index.js, validator/postWithWobjValidator.js
refactor post with wobjects parser, add validation on post wobjects(validate percents)
=> add validator for post with wobjects

test/factories/ObjectType/ObjectTypeFactory.js, test/parsers/voteParser/voteOnField/mocks.js, test/parsers/voteParser/voteOnField/test.js, utilities/helpers/voteFieldHelper.js
user can increase his own weight(expertize) in wobject though voting on append(update, field) only if it UpVote.
P.S.: before, user weigh increase on DownVote too
=> remove incr. weight in wobj. on Field DownVote

.gitignore, test/factories/ObjectType/ObjectTypeFactory.js, test/helpers/updateSpecifiedFields/test.js, test/models/ObjectTypeModel/test.js, test/validators/appendObjectValidator/test.js, utilities/constants.js, utilities/helpers/updateSpecificFieldsHelper.js, validator/appendObjectValidator.js
edit list of blacklist bots(remove waivio service bots)
=> add tagCategory and categoryItem field handlers, preCreate append validations

utilities/commentRefService/commentRefGetter.js
fix undefined name on wobj_type comment ref
=> fix when update redis cached refs

test/parsers/voteParser/voteOnField/test.js, test/steemApi/test.js, utilities/helpers/voteFieldHelper.js
was: percent % 100 === 0, now: percent % 10 === 0.
=> edit rule for field down vote

database/schemas/PostSchema.js, models/AppModel.js, test/models/AppModel/test.js, test/moderation/postModeration.js, utilities/helpers/votePostHelper.js, utilities/moderation/postModeration.js
add moderation to post by downvoting on this post from admin of moderator of specified app.
=> add handler for adding flags to blocked posts

parsers/postWithObjectParser.js, parsers/voteParser.js, utilities/guestOperations/customJsonOperations.js
add app validation on creating post not from commentParser.js, fix body and json_metadata null on creating from guest customJson handler
=> fix creating posts on guest votes

package.json, utilities/steemApi/postsUtil.js, utilities/tasks/addMissingPostsToUser/addMissingPostsToUser.js, utilities/tasks/addMissingPostsToUser/run.js
GIT-2228 add missing posts by username from hive databaseApi
=> GIT-2228 add missing posts

utilities/helpers/updatePostAfterComment.js
removed "/false" flag in hiveComment-expiredTTL & setted timer for 10 seconds
=> removed "/false" flag & setted 10 sec in timer

parsers/userParsers.js
added a field for info from which user the reblogging is performed
=> Fix reblog by guest user

utilities/notificationsApi/notificationsUtil.js
Changed the nesting depth of comments in the condition that determines whether it is a reply or not
=> Git-2816 fix notification on "Reply" to comment

database/schemas/AppSchema.js
changed the storage structure of cities in the field "configuration.availableCities" in App entity
=> Update storage structure of cities (For Home Page Task)

utilities/guestOperations/customJsonOperations.js, utilities/helpers/voteFieldHelper.js
added weight decrementation for guest user when he rejected field
=> (Git-2989) Fixed object search

constants/appData.js, models/PostModel.js, parsers/userParsers.js, test/helpers/postHelper/test.js, test/models/PostModel/test.js, test/parsers/userParsers/test.js, utilities/helpers/postHelper.js
added logic to remove objects from post if the author of post hide the comment in which the wobjects were mentioned
=> Added functionality for deleting objects mentioned in comments

database/schemas/UserSchema.js
=> (Git-2975) Nan-on-newest-user
